docs/CI-CD/centos-ci-cd.md, docs/README.md
Adding MD document with the howto steps and also the reference links.
Modifying the README to add a link to the new document.
=> Addind the CentOS ci-cd howto get an account

README.md
The referenced trello board is not being used anymore, so removing that reference
=> Remove reference to trello

events/2021-kubevirt-summit/proposals/privilege-dropping.md
**Abstract:**
KubeVirt's architecture is composed of two main components: virt-handler, a trusted DaemonSet, running in each node, which operates as the virtualization agent, and virt-launcher, an untrusted Kubernetes pod encapsulating a single libvirt + qemu process.
To reduce the attack surface of the overall solution, the untrusted virt-launcher component should run with as little linux capabilities as possible.
The goal of this talk is to explain the journey to get there, and the steps taken to drop CAPNETADMIN, and CAPNETRAW from the untrusted component.
This talk will encompass changes in KubeVirt and Libvirt, and requires some general prior information about networking (dhcp / L2 networking).
=> Propose privilege dropping presentation for KubevirtCon2021

events/2021-kubevirt-summit/proposals/migrating-vms-to-kubevirt-with-coriolis.md
KubeVirt opens scenarios for a Kubernetes based infrastructure that can handle both VMs and containers.
Wouldn't it be great to just automatically move all your Virtual Machines from legacy environments
and consolidate your whole infrastructure around Kubernetes and KubeVirt?
Coriolis performs automated migrations among most common clouds and virtualization solutions, like
VMware, OpenStack, AWS, Azure, AzureStack, OCI, Hyper-V and now also KubeVirt.
During this session we will perform a live demo showing how to migrate a VM from VMware vSphere to KubeVirt and
a separate demo showing the migration of a VM from OpenStack to KubeVirt.
=> KubevirtCon2021 proposal: Automated migration of Virtual Machines from VMware or OpenStack to KubeVirt

events/2021-kubevirt-summit/proposals/the-road-to-v1.md
This session is one of the "general interest" sessions planned for the Summit.
As the session program points to the proposal for details, this PR adds a description of that session so it can be linked the same way as the others.
=> Add information about the KubeVirt v1 session

go.mod, go.sum, sigs.yaml, validators/cmd/sigs/README.md, validators/cmd/sigs/sigs-validator.go
This PR adds a tool that can validate the basics of the `sigs.yaml` file. Currently it can validate/remove non existing links to owners elements.
Also it updates the sigs.yaml with removed unreachable owners links.
/cc @mazzystr @fabiand @fgimenez
=> Add sigs validator

GOVERNANCE.md, MAINTAINERS.md
Creates a GOVERNANCE.md file which outlines a simple self-selecting-council governance format.
This document is based on the CNCF Maintainer governance template.
Updated 6/26, Assumptions made in the new version per @fabiand:
1. ~~"Approver" in our membership docs is equivalent to "Maintainer".~~ Maintainers become a selected position, instead of the group of Approvers to kubevirt/kubevirt
2. CoC violations will be initially reported to the approvers before being escalated to the CNCF.
Unresolved Issues:
1. We need to clean up membership_policy.md so that it reflects our actual process of contributor advancement, particularly the ability to become Approver in a subproject, and that Approver means specifically root-level approver.
2. We also need a private mailing list for the collected …
=> Approver-led governance for Kubevirt

MAINTAINERS.md
* Commitment to the project: have they participated in discussions, 
contributions, and reviews for 1 year or more?
Ryan is working on various areas in the KubeVirt project since 2018.
* Does the person show leadership in one of these areas?
Ryan is leading a team of engineers at NVIDIA. He and his team are revealing and fixing issues in KubeVirt around performance and scale on bigger KubeVirt deployments which helps KubeVirt immensely.
He leads SIG performance which helps greatly coordinating performance and scale tasks across the whole projects,.
* Does the candidate bring new perspectives or community connections to the 
maintainers?
Yes, he helps a lot organizing efforts around performance and scale, bringing together different parties which can work in a coordinated fashion on these …
=> Add Ryan Hallisey as maintainer

proposals/governance/incubation_dd.md
Initial commit for CNCF incubating due diligence
We will submit this document to [toc/pulls ](https://github.com/cncf/toc/pulls)
Fixes #96 
doc built using accepted due diligence forms from [Falco](https://github.com/cncf/toc/pull/307/files) and [Thanos](https://github.com/cncf/toc/pull/342/files)
=> Initial commit for CNCF incubating due diligence

docs/README.md, docs/automating-github-org-management.md, member_dd/README.md
Replaces initial example PR for adding a member to the organization with a proper PR that adheres to the KubeVirt membership onboarding process. Adds a note at the top pointing towards the documentation for that process.
Besides that it fixes a couple of links that pointed to the old default branch name.
=> Add remark for KubeVirt org membership requirements

OWNERS
@mazzystr and myself stepped down from community management.
This is to reflect that change in the repo's OWNERS file.
Should we add others?
=> Update OWNERS: remove Chris and Pep

code-of-conduct.md
as requested by the TOC.
This merge must be endorsed by a majority of the KubeVirt Maintainers, since it changes our code of conduct.
Attn: @fabiand @rthallisey @vladikr @rmohr @stu-gott @vasiliy-ul @mazzystr @fgimenez
=> Swap our old CoC for the CNCF CoC,

MAINTAINERS.md
Andrew can help us as a community gardener.
=> maintainers: Welcome Andrew

sigs.yaml
Many repos have been switching away from "master" as the default
branch name. Any time "main" exists, assume it's the preferred
up-to-date branch name.
=> s/master/main/ wherever the URL resolves

design-proposals/flavors-and-preferences.md
KubeVirt's VirtualMachine API contains many advanced options for tuning
a virtual machine performance that goes beyond what typical users need
to be aware of. Users are unable to simply define the storage/network
they want assigned to their VM and then declare in broad terms what
quality of resources and kind of performance they need for their VM.
This design proposal sets of various changes to existing
VirtualMachineFlavor CRDs and the introduction of a new set of
VirtualMachinePreference CRDs to hopefully simplify the choices a user
has to make when defining a VirtualMachine to get the resources,
performance and guestOS characteristics they desire.
=> design-proposals: Refactor and extend the Flavors API 

design-proposals/default-instancetypes-from-volumes.md
This change introduces a design proposal setting out how default instancetypes could be inferred from volumes.
Signed-off-by: Lee Yarwood <lyarwood@redhat.com>
=> design-proposals: Default instance types inferred from volumes

contributors/contributing.md
**Description:**
Fixes broken link at 
**Broken Link:** https://kubevirt.io/user-guide/appendix/contributing/
**Fixed Link:** https://kubevirt.io/user-guide/contributing/
=> Fixed broken link to contributing user guide

design-proposals/cpu-hotplug.md
This design proposal is an alternative to https://github.com/kubevirt/community/pull/212
The key differences are:
- This proposal focuses on CPU hotplug, keeping in mind that the API will most likely be extended later for memory hotplug
- The implementation doesn't use the new Kubernetes vertical scaling API, as it not yet ready for production (currently in alpha stage). Instead, a live migration is used to scale the CPU resources up/down. However in the future, we definitely want to switch to using the vertical scaling API
- There's already a WIP/POC implementation of the design: https://github.com/kubevirt/kubevirt/pull/9401
=> CPU Hotplug design proposal

OWNERS
As a long-time kubevirt maintainer, Alona put under scrutiny all the critical network-related PRs proposed to the project in the last 3 years, making sure that new changes are not only technically correct, but that they also don't compromise maintainability of the codebase.
I would like to propose her to become an approver in the community repository as well, so she can take ownership over design proposals. I hope that this will improve our workflow and contributor experience, by discussing high level goals and APIs first, before we get into the weeds of implementation.
=> Adding Alona as an approver

design-proposals/monitoring-code-refactor/monitoring-code-refactor.md
This design doc is proposing a code refactor for the monitoring logic in all
KubeVirt components.
=> proposal: Monitoring code refactor

membership_checklist.md, membership_policy.md
Add a hint for new org members that they first need to accept the org invite before they become a full member.
/cc @aburdenthehand @alicefr @fabiand
=> Add hint to accept org invite for new members

design-proposals/passt-impl-iface-api-replacment.md
Following the emerging [Kubevirt Network Binding Plugin API](https://docs.google.com/document/d/13fLaqZuM8El_CT5XzxPv-1epKsB1-Spv_jtXveEkkdQ/edit#heading=h.z27rudfpwy44) and introduction of Passt network binding plugin https://github.com/kubevirt/kubevirt/pull/10425 https://github.com/kubevirt/kubevirt/pull/10621 
its now possible to remove Passt network binding implementation from Kubevirt core.
This PR introduces a plan for replacing Kubevirt's  core Passt binding implementation with the Passt network binding plugin.
=> Passt network interface API and implementation replacement

design-proposals/mass_machine_type_transition.md
When RHEL 10 is released, machine types prior to RHEL-9 will no longer be compatible. This proposes a method for users to mass update the machine types of any VMs with unsupported machine types while minimizing disruptions to workload.
=> Proposal: mass machine type transition

OWNERS
I think the community manager should be part of the approvers list.
/cc @fabiand @davidvossel @vladikr
=> community, owners: add aburdenthehand as approver

membership_policy.md
Adds a section to the membership policy that explains what inactive members are.
Fixes #
**Checklist**
```release-note
```
=> governance, kubevirt, org: add inactive member section

hack/generate-devstats-repo-sql.py, sigs.yaml
Remove some unusued sigs, focus on the essentials
Fixes #
sig-virtctl not in use: https://github.com/search?q=org%3Akubevirt%20sig-virtctl&type=code
sig virt not in use: https://github.com/search?q=org%3Akubevirt%20sig-virt&type=code
sig userinterface not in use: https://github.com/search?q=org%3Akubevirt%20sig-userinterface&type=code
**Checklist**
```release-note
NONE
```
=> SIGs: Remove some SIGs

design-proposals/descheduler-support.md
Add a design proposal to support running KubeVirt in a cluster that also has a descheduler. 
Fixes #
PR https://github.com/kubevirt/kubevirt/pull/11286 describes the current way KubeVirt handles eviction requests.
Descheduler proposal: https://github.com/kubernetes-sigs/descheduler/pull/1354
**Checklist**
```release-note
NONE
```
=> Design proposal: Descheduler support

design-proposals/volume-update-strategy.md
Third attempt and version for the volume migration
After several discussions, the API and solution diverged quite a lot from the original idea and CRD proposed in https://github.com/kubevirt/community/pull/245. Therefore, I decided to close the previous proposal and open a new PR.
This version introduces a new update strategy for volume under the VM spec and tries to follow the same flow as the cpu and memory hotplug described in the [cpu-hotplug proposal](https://github.com/kubevirt/community/blob/main/design-proposals/cpu-hotplug.md)
I think the most controversial part of this proposal is the data volumes restriction. In the previous proposal, it was the controller that was getting rid of the datavolume parts. Now, we want that only the user touches the VM spec, then the DV declarations …
=> design proposal: volume update strategy

sig-storage/charter.md
Extend sig-storage charter to include the group responsibilities and scope.
```release-note
NONE
```
=> sig-storage: extend charter with sig responsabilities

design-proposals/sdn-ipam-secondary-nets.md
This PR adds a design document outlining how to integrate the persistent IPs feature of the kubernetes multi-networking de-facto standard into KubeVirt.
Fixes #
**Checklist**
```release-note
NONE
```
=> ipam: integrate w/ k8s multi-network defacto standard persistent IPs

design-proposals/feature-lifecycle.md
Kubevirt requires a process with a clear policy on how features are introduced, evaluated and finally graduated or dropped.
This proposal defines the steps and policies to follow in order to manage a feature (lifecycle) in Kubevirt.
---
This work is attempting to formalize various discussions held at different occasions in the last few years.
Mostly triggered by the observation that we collect unused features and frag them for long periods with the need to maintain them in the codebase and documentation.
A previous draft version of this content has been started by @iholder101[^1].
It is a bit different in the format and focus, but it tried to solve the same challenge.
There has also been a fruitful discussion in the new sig-api, on several API stability topics[^2], some with strong …
=> design-proposal: Feature lifecycle

design-proposals/shadow-node.md
This PR is addressing a security issue [0][1] that exists because virt-handler is a daemonset that can patch the node. This proposal is presenting possible proposals to reduce virt-handler's node patching abilities to mitigate this issue.
[0] https://github.com/kubevirt/kubevirt/security/advisories/GHSA-cp96-jpmq-xrr2
[1] https://github.com/kubevirt/kubevirt/issues/9109
=> virt-handler: Restrict write access to nodes

sigs.yaml
Unfortunately the time zone is wrong for the meetings, this change corrects it to be CET, since the existing visitors all have agreed on the meeting time and we don't want to cause friction for existing visitors.
@aburdenthehand sorry for the hassle, could you please correct the time zone on the calendar entries for sig-ci to be `CET`?
Fixes #
/cc @aburdenthehand @brianmcarey 
**Checklist** …
=> sig-ci: correct meeting time zone

design-proposals/descheduler-support.md
The descheduler support design proposal specifies that a feature gate will be added.
The feature gate can be dropped, since no work is added other than to add annotations.
The feature gate drop also has the advantage of saving work to the cluster admins; with the feature gate, if a cluster admin wants to enable the descheduler, they have to install it and add the feature gate to KubeVirt.
Without the feature gate they only have to install it.
Also, this feature gate only enables a support for the descheduler, which should always be enabled, and there are no advantages to not have it.
Fixes # …
=> Drop feature gate in descheduler support design proposal

design-proposals/instancetype-vm-rollout-support.md
The [VM Rollout Strategy](https://kubevirt.io/user-guide/operations/vm_rollout_strategies/) feature introduced in [KubeVirt 1.2](https://github.com/kubevirt/kubevirt/releases/tag/v1.2.0) now allows for specific changes made to a running VM to propagate to the VMI without a restart. This design proposal covers extending this support to cover changes made to the referenced instance type or preference of a running VM.
Fixes #
**Checklist**
Approvers are expected to …
=> design-proposal: Introduce LiveUpdate support for instance types

sigs.yaml
This PR breaks the instance type feature out into a sub project [1] within the compute SIG.
The aim being to delegate ownership to individuals working in this area in an effort to help drive the API and overall feature towards v1 and GA. 
As sub projects have yet to be fully utilised within KubeVirt this PR also serves as a way to test out their use within the project given recent attempts to redefine and introduce working groups etc.
[1] https://github.com/kubernetes/community/blob/master/governance.md#subprojects
Fixes #
The associated OWNER_ALIASES changes …
=> sig-compute: Introduce instancetype sub project

GOVERNANCE.md, README.md, wg-TEMPLATE/README.md, wg-TEMPLATE/wg-charter-template.md
This PR:
* updates the document GOVERNANCE.md that describes SIGs and WGs.
* creates a template for working group definitions, aligned to how SIG templates currently look.
Fixes #
/cc @oshoval @fabiand
**Checklist**
```release-note
```
=> community, wg, template: create wg templates

membership_policy.md
As a followup to #301 this PR adds roles:
* SIG chair
* SIG Subproject Lead
* WG chair
Fixes a couple of header size issues in existing parts along the way.
Fixes #
**Checklist**
```release-note
```
=> membership, policy: add SIG, WG and subproject roles

OWNERS
I hereby nominate myself as a reviewer for the `kubevirt/community` repository, with the long term goal of becoming an approver.
I currently am one of the [SIG CI chairs](https://github.com/kubevirt/community/blob/main/sig-list.md#special-interest-groups) and also one of the SIG buildsystem chairs. I am employed by Red Hat and [active in the KubeVirt community since 2019](https://github.com/search?q=org%3Akubevirt+author%3Adhiller&type=issues&s=created&o=asc).
I have a [history of contributions](https://github.com/search?q=repo%3Akubevirt%2Fcommunity+author%3Adhiller&type=pullrequests) to this repository, where the main focus has been
* documentation of automation, 
* community processes and
* automatic document generation for community matters.
I would like to be a reviewer so that I can …
=> community,OWNERS: self nomination of dhiller as reviewer

design-proposals/dynamic-primary-pod-nic-name.md
This proposal proposes a mechanism to dynamically determine the primary pod interface for KuveVirt virtual machines (VMs).
The goal is to move away from the hard coded `eth0` interface and allow flexible, environment-driven interface
selection.
Fixes #
**Checklist**
```release-note
None
```
=> Design proposal: Support Dynamic Primary Pod NIC Name

design-proposals/primary_network_binding_for_seamless_migration.md
Choose the most appropriate Kubevirt network binding for the primary pod network, considering basic functionality support, including seamless migration.
Fixes #
**Checklist**
```release-note
NONE
```
=> design-proposal: Primary Network Binding for seamless migration

sigs.yaml, wg-arch-arm/charter.md, wg-arch-s390x/charter.md
PR #301 added the wg-TEMPLATE as a starting point for creating working groups.
This PR adds two initial wg-arch working groups:
* wg-arch-s390x
* wg-arch-arm
to define chairs and leads on S390x and ARM.
Also it defines subprojects in sig-buildsystem and sig-ci, so that arch wg members can own code.
Fixes #
=> community, wg, arch: add wg, sig subprojects and charter for S390x and ARM

sigs.yaml
/kind cleanup
Fixes indentation of `leads:` section below ci-390x subproject in sigs.yaml.
Fixes #
/cc @aburdenthehand
=> sigs.yaml: fix indentation of ci-s390x subproject

sig-list.md, sigs.yaml
Updates labels on sigs.yaml to the ones that exist and are used, where others that don't exist are removed.
Fixes #
/kind cleanup
/cc @aburdenthehand 
**Checklist**
```release-note
```
=> community,labels,sig-list: update/remove labels

design-proposals/instancetype.kubevirt.io/expand-during-submission.md
The initial design of instance types and preferences captured a point in time copy of the original resource for future use by the VirtualMachine to ensure we always generate the same VirtualMachineInstance at runtime.
This additionally allows users to easily switch between classes, sizes and generations of these resources at some point in the future. However this flexibility comes at the cost of complexity within KubeVirt itself especially handling more advanced VirtualMachine lifecycle flows.
This design proposal aims to set out a new cluster configurable to control how instance types and preferences are referenced from a VirtualMachine.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …
=> design-proposal: instancetype.kubevirt.io - Expand during submission

sig-list.md, sigs.yaml, wg-code-quality/wg-charter.md
Create wg charter and add sigs.yaml entry for wg-code-quality.
Update sig-list.md to reflect changes.
Fixes #327 
This PR needs to get rebased after https://github.com/kubevirt/community/pull/346 got in
=> community,wg,code-quality: establish working group code-quality 

design-proposals/instancetype.kubevirt.io/pkg-instancetype-refactor.md
This isn't required at all but I wanted to write down how I think we should go about refactoring the package.
Fixes #
**Checklist**
```release-note
NONE
```
=> design-proposal: instancetype.kubevirt.io - pkg/instancetype refactor

design-proposals/dynamic-primary-pod-nic-name.md
Fixes #
Extends the proposal proposed by #324.
**Checklist**
```release-note
NONE
```
=> Fix and extend the Dynamic Primary Pod NIC Name proposal to support rename

design-proposals/virtiofs-support/virtiofs-feature-gates.md
This design document explains how and why virtiofs feature gates should be adjusted. The main purpose is to avoid mixing feature control and configuration with feature enablement.
Fixes # [CNV-39324](https://issues.redhat.com/browse/CNV-39324)
**Checklist**
```release-note
Added proposal to introduce `EnableVirtioFsConfigVolumes` and `EnableVirtioFsPVC` feature gates.
```
=> design-proposal: Adjust virtiofs feature gates

design-proposals/node-labeller-refactor.md
The node-labeller has deviated from its primary purpose of simply labeling nodes. It now also handles inferring host capabilities for the vmcontroller, a task unrelated to its core function. Most of the capabilities it gathers aren't relevant to node labeling, leading to an overcomplicated design and unnecessary coupling with the vmcontroller which hinders testing and extensibility of both components.
As such this design proposal seeks to decouple the two and simplify node-labeller to focus on its original intended purpose while moving its current inference logic to a separate virt-handler unit. …
=> design-proposal: rewrite node-labeller to be more modular and testable 

design-proposals/new-proposals-framework.md
This PR is based on #288 and similarly suggests creating a new `kubevirt/enhancements `repository to manage KubeVirt Enhancement Proposals (VEPs). 
However, this proposal suggests a structured process for prioritizing enhancements, focusing review and development efforts, and improving collaboration across Special Interest Groups (SIGs). 
Each VEP will serve as the single source of truth for its feature, tracking its design, progress, and associated bugs, ensuring transparency and focus during development cycles.
```release-note
None
```
=> New process for handling virtualization proposals

design-proposals/hardening-vmim.md
In kubernetes we have two distinct pre-defined administrative roles:
- cluster-admin that is allowed to to perform any action on any resource
- admin that is allowed to read/write/amend almost all the resources in a namespace
We can assume that that granting to a developer/devops person the admin role to a namespace that he "owns" is a common practice.
In order to enqueue o cancel a live migration request, the user is supposed to create a `VirtualMachineInstanceMigration` object that is a namespaced resource that lives in
the same namespace of the VM object.
Till now, a namespace admin is allowed to create/delete `VirtualMachineInstanceMigration` objects in his namespaces.
The issue that this proposal is trying to address is that live migration is …
=> design-proposal: limit Live Migration initial permissions to cluster-admin

design-proposals/migration-target.md
Adding a design proposal to extend VirtualMachineInstanceMigration
object with an additional API to let a cluster admin
try to trigger a live migration of a VM injecting
on the fly and additional NodeSelector constraint.
The additional NodeSelector can only restrict the set
of Nodes that are valid target for the migration 
(eventually down to a single host).
All the affinity rules defined on the VM spec are still
going to be satisfied.
Fixes https://issues.redhat.com/browse/CNV-7075
Something like this was directly proposed/implemented with …
=> design-proposal: VirtualMachineInstanceMigration - Live migration to a named node

design-proposals/persist-vmi-firmware-uuid.md
This proposal introduces a mechanism to persist the FW ID of a Virtual Machine (VM) in KubeVirt. By storing the FW ID, we ensure that it remains consistent across VMI restarts, which is
crucial for applications and services that rely on the UUID for  identification or licensing purposes.
relates-to: https://github.com/kubevirt/kubevirt/issues/13156, https://github.com/kubevirt/kubevirt/pull/13158
**Checklist**
```release-note
None
```
=> design-proposal: improved handling of the VM FW ID

sig-list.md, sigs.yaml
Adds sig-compute meetings to sig.yaml.
Also, add the "sig-" prefix to sig names, like sig-network or sig-storage.
```release-note
sigs.yaml: add sig-compute meetings
```
=> sigs.yaml: add sig-compute meetings

design-proposals/helm-chart.md
This design proposal addresses the Helm chart installation method alternative. For reference: https://github.com/kubevirt/kubevirt/issues/8347
=> Add Helm charts proposal
