kubevirt/community

kvm-forum-hackfest-2017/README.md
To prepare the workshop around KVM Forum.
=> Add KVM Forum Workshop skel

README.md
There is a community calendar to keep track of community events and meetings.
=> README: Add the calendar

README.md
=> README: Just link to the calendar

events/2017-devconf-unconference/README.md, events/2017-devconf-unconference/intro.md, events/2017-devconf-unconference/patterns.md
=> events: Add lost 2017 devcofn

events/2019-kubecon-eu/minutes.md
=> small nits

OWNERS
* List reviewers and approvers
=> feat: add owners file

docs/CI-CD/how-to-prow.md, docs/CI-CD/prow-jobs.md, docs/README.md, docs/off-topic/how-to-bazel.md
- Added documentation about how Prow works and how do we have it integrated on community repos
- Added documentation about how to create jobs on Prow in order to manage the repository testing
- Added some information about how to start with Bazel
=> Feat: Added documentation section, created CI/CD and Offtopic inside

OWNERS
https://www.youtube.com/watch?v=EecgsR5ZaQM
=> Add Pedro to owners

events/2019-kubecon-na/README.md
Adding initial content to prepare an on-site meetup during the upcoming KubeCon in San Diego
=> Initial content for meetup during KubeCon NA 2019

events/2019-kubecon-na/README.md
Updated the KubeCon meetup README with information about the location of the event.
Also added an initial agenda item.
Signed-off-by: Pep Turró Mauri <pep@redhat.com>
=> Add KubeCon meetup location

events/2019-kubecon-na/README.md
Received details about the specific room name for the meetup, adding it here.
=> Add room details to kubecon meetup

docs/off-topic/recording-videos.md
Some video tips from colleagues for recording better videos and audios for demos
=> Tips for video recording

docs/article-workflow.md
Document article workflow and troubleshooting  local vs CI/CD
FIle at: https://github.com/kubevirt/community/blob/f19cc78a7775e5086ebbe6ad84b4fdeac74fd4ff/docs/article-workflow.md
=> Document workflow

events/2021-kubevirt-summit/proposals/proposal-template.md
An initial basic template to submit content proposals for the upcoming KubeVirt online event
=> Add template for content proposals for the KubeVirt summit

events/2021-kubevirt-summit/proposals/snapshot-dev.md, events/2021-kubevirt-summit/proposals/vm-snapshots.md
Signed-off-by: Michael Henriksen <mhenriks@redhat.com>
=> proposal for vm snapshot session

events/2021-kubevirt-summit/proposals/vm-batch-api.md
Signed-off-by: Ryan Hallisey <rhallisey@nvidia.com>
=> Batch VM API 2021 summit proposal

events/2021-kubevirt-summit/proposals/prow-jobs-automated-testing.md
Signed-off-by: Daniel Hiller <dhiller@redhat.com>
=> KubeVirt summit session proposal: "How to avoid merging broken code with automated testing using prow"

events/2021-kubevirt-summit/proposals/proposal-awels.md
Signed-off-by: Alexander Wels <awels@redhat.com>
=> proposal for kubevirt hotplug session

events/2021-kubevirt-summit/proposals/cpu-pinning.md
Signed-off-by: Dhanya Bhat <dbhat@nvidia.com>
=> add CPU pinning proposal

events/2021-kubevirt-summit/proposals/harvester.md
Hi,
I'd like to propose a talk about Harvester and KubeVirt. Harvester(https://github.com/rancher/harvester) is a new open-source HCI solution that heavily depends on KubeVirt for the virtualization part. We'd like to share some experiences from the user's perspective on KubeVirt, and the story of how we integrated KubeVirt with Harvester.
Thanks.
=> KubeVirt Summit 2021 proposal: Harvester with KubeVirt

events/2021-kubevirt-summit/proposals/pci-passthrough.md
Submitting this on behalf of the presenters as per email discussions.
=> KubeVirt Summit 2021 session proposal: PCI passthrough

events/2021-kubevirt-summit/proposals/user-story-vfx-production.md
Our experience integrating Kubevirt into our existing Kubernetes stack, in a short time frame, for a highly demanding use-case.
=> Summit 2021: User Story: Moving a VFX Studio to the Cloud with Kubernetes and Kubevirt

events/2021-kubevirt-summit/proposals/kubevirt-vmio.md
Signed-off-by: Jakub Dzon <jdzon@redhat.com>
=> Proposal: Moving oVirt and VMware VMs to KubeVirt with VM Import Operator and Forklift

events/2021-kubevirt-summit/proposals/molecule-kubevirt.md
Hi, 
I'm working on a Kubevirt driver for Ansible Molecule and I propose to explain and demo it. 
Please find details in markdown. 
Regards.
=> Propose molecule-kubevirt presentation

events/2021-kubevirt-summit/proposals/common-templates.md
Signed-off-by: Karel Simon <ksimon@redhat.com>
=> Proposal: common-templates

events/2021-kubevirt-summit/proposals/sriov-live-migration.md
Signed-off-by: Or Mergi <ormergi@redhat.com>
=> Propose session about SRIOV Live Migration

events/2021-kubevirt-summit/proposals/hco-user-proposal-2021.md
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>
=> change presentes for the HCO talk

docs/README.md, docs/automating-github-org-management.md
=> Add documentation of KubeVirt GitHub org management

membership_checklist.md, membership_policy.md
Initial commit for new membership policy page
> Fixes #75
=> Initial commit for new membership policy page

member_dd/README.md
Initial commit to create member_dd directory and simple README.md
=> Initial commit to create member_dd directory and simple README.md

design-proposals/README.md, design-proposals/proposal-template.md
This documents the process outlined in the google doc here, https://docs.google.com/document/d/1VjJfuvsg1wgk4FuWD0tZENejl7wJkrWCAMRk9IbHrbQ/edit#heading=h.pg8ybhpaegv0
I've introduced two changes.
- Update the proposal template outline
- README briefly describing the design proposal process
=> Design proposal process documentation

responsibilities/community_meeting.md
I would like to document how organizers should handle the community meeting.
Initial commit.  :)
=> Initial commit for community meeting page

conference-proposals/2021-all-things-open/README.md
Presentation proposal for All Things Open - 2021
=> Presentation proposal for All Things Open - 2021

docs/README.md, docs/add-merge-automation-to-your-repository.md
=> Add automatic merge config setup docs

OWNERS
Signed-off-by: cwilkers <cwilkers@redhat.com>
=> Added self as reviewer, approver

membership_policy.md
Signed-off-by: Dominik Holler <dholler@redhat.com>
=> Fix link in membership_policy.md

proposals/governance/incubation_dd.md
Signed-off-by: Chris Callegari <mazzystr@gmail.com>
Peer review notes: This is real easy.  I'm just syncing diffs from CNCF/ToC pull req peer review ([link](https://github.com/cncf/toc/pull/715))
=> Updates per upstream CNCF/ToC peer review

design-proposals/golden-image-delivery-and-update-pipeline.md
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>
=> proposal for HCO implementation of the golden image feature

events/2021-10-18-ATO2021/README.md
Signed-off-by: Chris Callegari <mazzystr@gmail.com>
=> Initial commit

design-proposals/migration-policies.md
Design proposal for Migration Policies following the [design process](https://github.com/kubevirt/community/blob/main/design-proposals/README.md).
- [Proposal in readable format](https://github.com/kubevirt/community/blob/9a28992826f369e57dae16f86fe39e03faacf772/design-proposals/migration-policies.md)
- [Implementation PR](https://github.com/kubevirt/kubevirt/pull/6399)
- [Old Design Document](https://docs.google.com/document/d/14KYrdXtrgooq5dswgWMfscVF3vNySLI3Syp8Ie37BTI/edit)
=> Add design proposal for MigrationPolicy

design-proposals/amd-sev.md
Initial design proposal targeting the support of confidential computing with AMD SEV in KubeVirt.
PoC PR (launching of SEV VMs, no attestation): https://github.com/kubevirt/kubevirt/pull/6166
=> Design Proposal: AMD SEV support in KubeVirt

OWNERS
It is an oversight that they are not approvers.
=> Adding David and Vladik as approvers

design-proposals/VM-cloning.md
A design proposal for VM cloning.
* [Design Proposal in human readable format](https://github.com/kubevirt/community/blob/98d2aeb59ff8f70a62daad435641ffb7f485f770/design-proposals/VM-cloning.md)
=> VM Cloning design proposal

design-proposals/export-import/volume-export.md
Signed-off-by: Michael Henriksen <mhenriks@redhat.com>
Supersedes: #155
=> Virtual Machine "raw" volume export proposal

design-proposals/garbage-collect-completed-dvs.md
Signed-off-by: Arnon Gilboa <agilboa@redhat.com>
=> Garbage Collect Completed DVs - Design Proposal

design-proposals/vm-memory-dump.md
Signed-off-by: Shelly Kagan <skagan@redhat.com>
=> VM memory dump design proposal

membership_policy.md
Hello everyone,
This PR aims to introduce a small update in the membership policy so the requirements for sponsors are better explained.
Best regards.
=> Update membership-policy to specify valid OWNERS files in sponsor requirements

design-proposals/sriov-interfaces-mapping.md
This is a design proposal for fixing Kubevirt's SR-IOV interfaces assignment logic, following kubevirt/kubevirt#7444.
*When reviewing use the option to `view file` from the menu on the upper right hand to view the markdown formatting.
Signed-off-by: Or Mergi <ormergi@redhat.com>
=> proposal: SR-IOV Interfaces Assignment Fix 

design-proposals/guest-agent-exec.md
Proposal to add `virtctl ga-exec` command.
Design document - https://docs.google.com/document/d/1IYTJEWskdig_j83QgfEPQxbg5ui1uvtiVAYOL0RixI8/edit?usp=sharing
Relates to: https://github.com/kubevirt/kubevirt/issues/8680
=> Virtctl guest agent exec

design-proposals/multiarch-cluster.md
The purpose of this PR is to add the proposal document outlining the support for multi-architecture clusters for KubeVirt
=> Added proposal for multi-architecture cluster support to KubeVirt

design-proposals/default-virt-storage-class.md
This design presents a possible way of steering kubevirt users
towards using a specific set of backend storage parameters for provisioning VM disks
=> Proposal: default virtualization storage class

contributors/help-wanted.md
Adds an initial help wanted markdown file copied from k8s, so that we can target the prow help plugin to it.
Fixes #
/cc @aburdenthehand @fabiand 
**Checklist**
```release-note
```
=> community: add help-wanted.md

sig-observability/charter.md
Add sig-observability charter
**Checklist**
```release-note
NONE
```
=> Add sig-observability charter

sig-network/charter.md
Adding a sig-network charter.
Fixes #
**Checklist**
```release-note
None
```
=> sig-network charter

sigs.yaml
Follow up on https://github.com/kubevirt/community/pull/282, adds sig-observability to sigs.yaml
/cc @sradco @fabiand 
Fixes #
**Checklist**
```release-note
NONE
```
=> Add sig-observability to sigs.yaml

design-proposals/kubevirtbmc.md
Propose [KubeBMC](https://github.com/starbops/kubebmc), enabling a way to do out-of-band management against VMs using IPMI/Redfish just like what we do to bare-metal servers, to the KubeVirt ecosystem.
Related issue: kubevirt/kubevirt#9108
**Checklist**
```release-note
NONE
```
=> Proposal: KubeVirtBMC

design-proposals/network-binding-plugin/network-binding-plugin.md
Design proposal to extend the network binding plugin entry in the kubevirt CR with an option for a downward API.
When specified, a downwardAPI from the virt-launcher pod to the binding sidecar will be added.
Currently the only supported downward API is "device-info", exposing the a map between the logical network name to its network status annotation device info.
Fixes #
**Checklist**
```release-note …
```
=> network binding plugin: DownwardAPI for device info

sig-TEMPLATE/sig-charter-template-prefilled.md, sig-TEMPLATE/sig-charter-template.md, sig-buildsystem/charter.md, sigs.yaml
Adds the `sig-buildsystem` definition and adds the sig to the sigs.yaml
Fixes #
/cc @brianmcarey @xpivarc
**Checklist**
```release-note
add sig-buildsystem
```
=> kubevirt, sig-buildsystem: add charter and entry in sigs.yaml

sig-compute/charter.md, sigs.yaml
Introduces a sig-compute charter.
See https://github.com/kubevirt/community/blob/main/sig-TEMPLATE/README.md for more info.
```release-note
NONE
```
=> Introduce a sig-compute charter

sig-ci/charter.md, sigs.yaml
Adds the charter and sigs.yaml entry for the `sig-ci`. This is done to make clear the responsibilities that are different from `sig-buildsystem`.
Fixes #
/cc @brianmcarey @fabiand
**Checklist**
```release-note
```
=> kubevirt, sig-ci: add charter and entry in sigs.yaml

sig-compute/charter.md, sig-scale/charter.md, sigs.yaml
Update Sig-Scale charter
```release-note
NONE
```
=> Update sig-scale charter

OWNERS
I've been a reviewer for a few years now, and this repository lacks active approvers, so this is my nomination.
/cc @aburdenthehand @AlonaKaplan @cwilkers @davidvossel @fabiand @rmohr @vladikr
=> owners: adding myself as an approver

sigs.yaml
Updates owners references to projects that are relevant to sig-network wrt KubeVirt.
Fixes #
/cc @phoracek
=> sigs.yaml,sig-network: update owner references

sigs.yaml
Update the sig-network subprojects, each focusing on a specific repo.
Leads for each have been updated.
Fixes #
Secondary leads are highly recommended, but it is our of this change scope.
Each subproject lead should try and find another leader to assure availability.
**Checklist**
```release-note
NONE
```
=> sigs: Update the sig-network subprojects

membership_policy.md
Updates the link to the devstats dashboard used to measure inactivity of org members. This now links to the developer activity count.
/cc @aburdenthehand 
Fixes #
=> community,membership policy: update devstats link

design-proposals/feature-lifecycle.md
Make English clearer
```release-note
NONE
```
=> Update feature-lifecycle.md to make the purpose of a subsection clearer

sigs.yaml
Fixes #
**Checklist**
```release-note
```
=> chore(sigs.yaml): Add missing dir to sig-compute-instancetype

sigs.yaml
Add the sig-compute-virtctl subproject to sigs.yaml.
See https://github.com/kubevirt/kubevirt/pull/13677
Fixes #
**Checklist**
```release-note
None
```
=> sigs.yaml: Add sig-compute-virtctl subproject

design-proposals/proposal-template.md
This PR adds a new security-related section to the design proposal template to cover all associated security risks
```release-note
NONE
```
=> New Security Section

CNCF/general_technical_review.md
This is a general technical review of the KubeVirt project.
It is document is required for KubeVirt's graduation application
Fixes #345 
```release-note
NONE
```
=> General technical review of the KubeVirt project

docs/add-merge-automation-to-your-repository.md
A couple of links were outdated after the move of prow from test-infra into it's own repo.
Also updated the example workflow for readability.
Fixes #
/cc @aburdenthehand
=> fix: update links in merge automation doc

sig-compute/charter.md
Fixes a spelling, adds github profile links.
Fixes #
/cc @iholder101 @jean-edouard
=> fix(spelling): sig-compute charter.md
